// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFCoreTest.Models;

public partial class License
{
    public string IdLicense { get; set; }

    public string IssuedBy { get; set; }

    public short Type { get; set; }

    public int Limit { get; set; }

    public DateTime? Activated { get; set; }

    public string IdPartner { get; set; }

    public string SerialNo { get; set; }

    public bool? IsActive { get; set; }

    public short? IdDescription { get; set; }

    public decimal? Iznos { get; set; }

    public DateTime? DatumFakturisanja { get; set; }

    public int? UgovoreniLimit { get; set; }

    public int? LimitRelated { get; set; }
}